Fix gcc11-compat and merge to CELLINKAB/master
CELLINKAB/Slic3r pull request #6
Opened 2024-04-22 07:49 UTC by marcus-sonestedt

Our master is not directly mergeable to base repo's master (which is c++ only, and has tons more fixes) though, but this is a step forward.

Will do some checking to see if this helps with slicing issues. Hopefully it allows us to run unit tests with slicer on Jenkins again (that uses docker images with Ubuntu 22 as base) at least.

Note that this slicer does not run on Ubuntu 20 due to glibc 2.33 or 2.34 required by the local-perl exe. Not sure if we need to fix that. I looked into how to install other glibc verisons on ubuntu and.. ugh.. I built it a newer one on my laptop at least, so we can probably work around it if required.

Includes changes from #5 and #3 too.

2024-04-25 08:22 UTC, MilanIvezic approved these changes

2024-04-25 08:23 UTC, edmundwatson commented
I though we used the heartware branch  it turns out we use "test" 
WHY?
https://github.com/CELLINKAB/meta-shared/blob/d37895e27e98367ee903b9b4d6e119d5c69956d6/recipes-slicer/slic3r/slic3r_git.bb#L9

2024-04-25 08:23 UTC, edmundwatson requested changes
Which branch?

2024-04-25 08:33 UTC, marcus-sonestedt commented
> Which branch?

I figured merging to master in our repo made sense. test branch is already a parent, so is heartware branch. So we're getting everything.

![image](https://github.com/CELLINKAB/Slic3r/assets/43488/39d1143b-af64-42ac-b568-eb29044ca3e7)

2024-04-25 12:17 UTC, marcus-sonestedt commented
Hm, I should probably do a test build in Yocto with this slicer to see that it works there before we merge this.

2024-04-26 06:32 UTC, marcus-sonestedt commented
> Hm, I should probably do a test build in Yocto with this slicer to see that it works there before we merge this.

I did. Patching before build failed: https://jenkins.cellink.dev/job/foton/job/FotonOS%20Dev%20Image/job/build%252Ffeature/254/console

More work needed.

2025-06-04 08:07 UTC, marcus-sonestedt commented
Closing out PRs that I am not working on/with anymore. Anyone else is free to reopen branch and continue.

2025-06-04 08:07 UTC, closed without merging